### ISSUE TITLE
Can you explain the .map(drop) in usage example?

### ISSUE THREAD

**Issue by Nagidal** [yaahc/color-eyre#116]
Hi, I'm quite new to rust and I'm just starting to use this library for better error output. I don't understand how can the `usage.rs` example even run. There is [this line](https://github.com/yaahc/color-eyre/blob/4a7b4d6988c6b0da5e04e29c9d6e10595b5dc302/examples/usage.rs#L35) with `.map(drop)` which is completely obscure to me. As far as I have learned, map expects a Closure, but `drop` does not look like a closure, nor has it been defined as a variable. What does it do?

If `drop` is a function which is in scope by default, it could be [https://doc.rust-lang.org/stable/std/ops/trait.Drop.html](https://doc.rust-lang.org/stable/std/ops/trait.Drop.html), which one tries to execute on a String. But since String is Clone (not Drop), it produces some sort of an error, is that it?

**Comment by yaahc** [comment]
Happy to explain!

The `drop` there is referring to `std::mem::drop`[^1], which is a free function in the prelude[^2] not a closure: 

The reason this works with `map` is because `map` expects any arbitrary type that implements the `FnOnce(T) -> U` trait, which is implemented automatically for both closures and for functions. The end result is that `drop` ends up being called on the `String` from the previous function in the `Ok` case which just throws it away and replaces it with the unit type `()` aka nothing. 

[^1]: https://doc.rust-lang.org/stable/std/mem/fn.drop.html
[^2]: https://doc.rust-lang.org/stable/std/prelude/index.html

**Comment by Nagidal** [comment]
Thank you very much for the thorough explanation. It helped me to learn a great deal of rust basics as I followed the paths in this rabbit hole.
