### ISSUE TITLE
Discussion: Allowing `.suggestion()` and other sections on `eyre!()` macro.

### ISSUE THREAD

**Issue by SecurityInsanity** [yaahc/color-eyre#34]
:wave: Hey! I've been porting my crate to use `color-eyre`, and this particular application has quite a few "recoverable" errors (perhaps a better word is "warnings" here), but I'd still like to log to the user. I'd like to keep the formatting the same between unrecoverable errors, and recoverable errors I've been doing a pattern where I manually create an error, and just call `unwrap_err()`:

```rust
use color_eyre::{eyre::eyre, section::help::Help, Report};
use tracing::warn;

warn!(
    "{:?}",
    Err::<(), Report>(eyre!(
        "Mount String for Docker Executor: [{}] is invalid, missing path for container. Will not mount.",
        item,
    ))
    .note("Mounts should be in the format: `host_path:path_in_container`")
    .unwrap_err()
);
```

---

This is because `eyre!` does not seem to return something that can have sections on it:

Source Code:

```rust
use color_eyre::{eyre::eyre, section::help::Help, Report};
use tracing::warn;

warn!(
    "{:?}",
    eyre!(
        "Mount String for Docker Executor: [{}] is invalid, missing path for container. Will not mount.",
        item,
    ).note("Mounts should be in the format: `host_path:path_in_container`")
);
```

Compiler Error:

```txt
error[E0599]: no method named `note` found for struct `eyre::Report<_>` in the current scope
 --> src/executors/docker.rs:311:10
    |
311 |                             ).note("Mounts should be in the format: `host_path:path_in_container`")
    |                               ^^^^ method not found in `eyre::Report<_>`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0599`.
```

---

I realize this isn't necessarily an error, so I realize it may not exactly fit in the crate, but I figured it'd at least be worth discussion about best path forward since it doesn't feel like a totally unique problem too.

**Comment by yaahc** [comment]
This is caused by the separation between `eyre` and `color-eyre` and the way its currently designed. The `eyre!` macro is exported by the `eyre` crate, which knows nothing about `color-eyre` or its notion of sections. The type that is returned from `eyre!` is a `Report<H>` where `H` hasn't been resolved. And then, to make this all worse the `note` function and other section modifying functions are similarly defined outside of `eyre` via an extension trait. It might be possible for me to add an identical trait to `SectionExt` that works directly on `Report` rather than being a combinator that applies to `Report`s inside of `Result`s, so it might be possible to fix this but ultimately it doesn't matter. All of this boils down to the fact that `eyre`'s `0.4` release depends on generics to specify the handler type. The next release of `eyre`, which I'm aiming to get out today removes the generic parameter and instead uses a globally installed hook to construct handler trait objects which can be boxed and stored by `eyre!`. On the next release this should "just work".

**Comment by SecurityInsanity** [comment]
Sounds great @yaahc , thanks for the quick, and helpful response :heart: !

**Comment by yaahc** [comment]
My pleasure, ty for the helpful suggestions!

side note, if you're interested in trialing the new release and helping me catch any issues I may have missed pre release now is the time. The only thing left to do is to update the documentation to reflect the new reality of how everything works and possibly tweek a few of the interfaces to be easier to use.
