### ISSUE TITLE
Direct access to panic handler (to combine it with other panic handlers)

### ISSUE THREAD

**Issue by kellpossible** [yaahc/color-eyre#66]
It would be nice to have something like https://docs.rs/color-backtrace/0.4.2/color_backtrace/struct.BacktracePrinter.html#method.into_panic_handler for `HookBuilder` so the panic handler could be combined with other panic handlers in the rust ecosystem without installing it.

**Comment by kellpossible** [comment]
The same goal could also probably be achieved with a simple change to make `print_panic_info()` public.

**Comment by yaahc** [comment]
Sounds like a great idea :D 

Some Suggestions:

- Instead of exposing a method to convert into the `Box<dyn Fn...>` implement the `Into` trait
- remove the `install_panic_hook` fn and add an `install` fn to both `EyreHook` and `PanicHook` that calls the relevant `set_hook(self.into());
- remove `installed_printer()` entirely and copy the appropriate filters needed by Eyre when printing backtraces into the eyre hook

**Comment by kellpossible** [comment]
Thanks, those seem like great suggestions! :+1:

**Comment by kellpossible** [comment]
@yaahc I'm guessing you've already implemented them in the commits you pushed yesterday?

**Comment by yaahc** [comment]
heh, yea for the most part. I think I'm going to still add an `into_panic_hook` and `into_eyre_hook` because when you want to wrap the color-eyre hooks the `into` fn needs type annotations and getting them right is super cumbersome. Just missing a `Send` bound will break things for example. Overall though I'm pretty excited about this change.

**Comment by yaahc** [comment]
closed by #67
